### ISSUE TITLE
Unexpected space in header value

### ISSUE THREAD

**Issue by patrikmor** [nickgammon/HTTPserver#2]
First of all I want to thank you for this very useful library.
I found that in header values is added one space at the end.
Is it for some purpose or is it a error in parsing?
I'm using a simple authentication by header parameters and this behavior causing problems to me.

**Comment by nickgammon** [comment]
Fixed in this commit: https://github.com/nickgammon/HTTPserver/commit/6a213cceb92127d3a4a543edb1df5dd3ad81502d
